apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
stringData:
  jwt.hex: "0x9c97959acac41b27472db61a5ad71c72ffce2cbc3df7edf16954ab0db3f7da4d" # Replace with a secure random 32-byte hexadecimal string
