
apiVersion: apps/v1
kind: Deployment
metadata:
  name: geth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geth
  template:
    metadata:
      labels:
        app: geth
    spec:
      tolerations:
      - effect: NoSchedule
        operator: Exists
      containers:
      - name: geth
        image: ethereum/client-go:latest
        args:
        - "--datadir=/data"
        - "--sepolia"
        - "--syncmode=full"
        - "--http"
        - "--http.addr=0.0.0.0"
        - "--http.port=8545"
        - "--http.api=eth,net,engine,admin"
        - "--authrpc.addr=0.0.0.0"
        - "--authrpc.port=8551"
        - "--authrpc.vhosts=*"
        - "--authrpc.jwtsecret=/jwt/jwt.hex"
        ports:
        - containerPort: 8545
        - containerPort: 8551
        volumeMounts:
        - name: geth-storage
          mountPath: /data
        - name: jwt-secret
          mountPath: /jwt
          readOnly: true
      volumes:
      - name: geth-storage
        persistentVolumeClaim:
          claimName: geth-pvc
      - name: jwt-secret
        secret:
          secretName: jwt-secret
---
