apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ethereum-storage
provisioner: kubernetes.io/azure-disk
parameters:
  storageAccountType: Premium_LRS
  kind: Managed
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
