apiVersion: v1
kind: Service
metadata:
  name: prysm-service
spec:
  selector:
    app: prysm
  ports:
  - port: 13000
    targetPort: 13000
    name: tcp
  - port: 12000
    targetPort: 12000
    name: udp
  type: ClusterIP
